//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_BTL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoKTEntities : DbContext
    {
        public DemoKTEntities()
            : base("name=DemoKTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<Khu_nha> Khu_nha { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<Que> Ques { get; set; }
        public virtual DbSet<Sinhvien> Sinhviens { get; set; }
        public virtual DbSet<Thiet_Bi> Thiet_Bi { get; set; }
        public virtual DbSet<Thuephong> Thuephongs { get; set; }
        public virtual DbSet<Thutienphong> Thutienphongs { get; set; }
        public virtual DbSet<Thietbi_Phong> Thietbi_Phong { get; set; }
        public virtual DbSet<Traphong> Traphongs { get; set; }
    }
}
