//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinhvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sinhvien()
        {
            this.Thuephongs = new HashSet<Thuephong>();
        }
    
        public string Ma_sv { get; set; }
        public string Ten_sv { get; set; }
        public System.DateTime Ngaysinh { get; set; }
        public string Gioitinh { get; set; }
        public string Maque { get; set; }
        public string Makhoa { get; set; }
        public string Malop { get; set; }
    
        public virtual Khoa Khoa { get; set; }
        public virtual Lop Lop { get; set; }
        public virtual Que Que { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thuephong> Thuephongs { get; set; }
    }
}
