//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thietbi_Phong
    {
        public string Ma_Phong { get; set; }
        public string Ma_Thiet_Bi { get; set; }
        public Nullable<int> So_Luong { get; set; }
        public string Tinh_Trang { get; set; }
    
        public virtual Phong Phong { get; set; }
        public virtual Thiet_Bi Thiet_Bi { get; set; }
    }
}
