//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thiet_Bi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thiet_Bi()
        {
            this.Thietbi_Phong = new HashSet<Thietbi_Phong>();
        }
    
        public string Ma_Thiet_Bi { get; set; }
        public string Ten_Thiet_Bi { get; set; }
        public decimal Gia_Tri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thietbi_Phong> Thietbi_Phong { get; set; }
    }
}
