//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thuephong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thuephong()
        {
            this.Traphongs = new HashSet<Traphong>();
        }
    
        public string Masothue { get; set; }
        public string Ma_sv { get; set; }
        public string Ma_Phong { get; set; }
        public System.DateTime NgayBDau { get; set; }
        public System.DateTime Ngaykt { get; set; }
        public string Ghichu { get; set; }
    
        public virtual Phong Phong { get; set; }
        public virtual Sinhvien Sinhvien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traphong> Traphongs { get; set; }
    }
}
