//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thutienphong
    {
        public string Ma_Phong { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public decimal Tiennha { get; set; }
        public decimal Tiendien { get; set; }
        public decimal Tiennuoc { get; set; }
        public decimal Tienvesinh { get; set; }
        public Nullable<decimal> Tienphat { get; set; }
        public System.DateTime Ngayhethan { get; set; }
        public System.DateTime Ngaydong { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
